module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.27,True,2022-11-10T07:00:13,,
cowidev.vax.batch.australia,,,2022-11-10T07:00:10,,
cowidev.vax.batch.austria,1.75,True,2022-11-10T07:00:11,,
cowidev.vax.batch.belgium,1.94,True,2022-11-10T07:00:12,,
cowidev.vax.batch.bolivia,1.89,True,2022-11-10T07:00:12,,
cowidev.vax.batch.canada,20.79,False,2022-11-10T08:09:48,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 284, in main
    Canada().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 268, in export
    df, df_age, df_man = self.read(), self.read_age(), self.read_manufacturer()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 99, in read_age
    check_known_columns(
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 168, in check_known_columns
    raise Exception(f""Previous column(s) missing: {missing_cols}"")
Exception: Previous column(s) missing: {'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 18', 'Unnamed: 21'}
","Previous column(s) missing: {'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 18', 'Unnamed: 21'}"
cowidev.vax.batch.chile,1.02,True,2022-11-10T07:00:13,,
cowidev.vax.batch.czechia,3.62,True,2022-11-10T07:00:15,,
cowidev.vax.batch.denmark,4.18,True,2022-11-10T07:00:16,,
cowidev.vax.batch.ecdc,82.21,True,2022-11-10T08:09:28,,
cowidev.vax.batch.ecuador,1.95,True,2022-11-10T07:00:15,,
cowidev.vax.batch.estonia,0.66,True,2022-11-10T07:00:16,,
cowidev.vax.batch.france,0.45,True,2022-11-10T07:00:16,,
cowidev.vax.batch.germany,1.91,True,2022-11-10T07:00:18,,
cowidev.vax.batch.greece,2.81,True,2022-11-10T07:00:19,,
cowidev.vax.batch.hong_kong,13.58,True,2022-11-10T07:00:29,,
cowidev.vax.batch.indonesia,,,2022-11-10T07:00:17,,
cowidev.vax.batch.ireland,1.0,True,2022-11-10T07:00:18,,
cowidev.vax.batch.israel,9.81,True,2022-11-10T07:00:27,,
cowidev.vax.batch.italy,11.95,True,2022-11-10T07:00:30,,
cowidev.vax.batch.japan,18.96,True,2022-11-10T08:08:24,,
cowidev.vax.batch.jersey,1.57,True,2022-11-10T07:00:22,,
cowidev.vax.batch.latvia,25.86,True,2022-11-10T07:00:47,,
cowidev.vax.batch.lithuania,1.99,True,2022-11-10T07:00:29,,
cowidev.vax.batch.luxembourg,1.6,True,2022-11-10T07:00:31,,
cowidev.vax.batch.malaysia,0.75,True,2022-11-10T07:00:30,,
cowidev.vax.batch.malta,0.75,True,2022-11-10T07:00:30,,
cowidev.vax.batch.netherlands,,,2022-11-10T07:00:30,,
cowidev.vax.batch.new_zealand,12.01,True,2022-11-10T07:00:42,,
cowidev.vax.batch.norway,0.69,True,2022-11-10T07:00:31,,
cowidev.vax.batch.peru,4.73,True,2022-11-10T07:00:36,,
cowidev.vax.batch.portugal,,,2022-11-10T07:00:31,,
cowidev.vax.batch.romania,15.2,True,2022-11-10T07:00:46,,
cowidev.vax.batch.saudi_arabia,10.86,True,2022-11-10T07:00:47,,
cowidev.vax.batch.singapore,2.21,True,2022-11-10T07:00:44,,
cowidev.vax.batch.slovakia,39.86,True,2022-11-10T07:01:24,,
cowidev.vax.batch.slovenia,0.31,True,2022-11-10T07:00:46,,
cowidev.vax.batch.south_korea,38.76,True,2022-11-10T07:01:25,,
cowidev.vax.batch.spc,16.7,True,2022-11-10T07:01:03,,
cowidev.vax.batch.sweden,21.21,False,2022-11-10T08:10:10,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 244, in main
    Sweden().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 238, in export
    df = self.read().pipe(self.pipeline)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/batch/sweden.py"", line 144, in pipeline
    .pipe(make_monotonic)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/utils/utils.py"", line 44, in make_monotonic
    raise Exception(
Exception: 51 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date location                                         source_url  ... people_vaccinated  people_fully_vaccinated  total_boosters
46  2021-11-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7392904                  6925338            <NA>
47  2021-11-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7436125                  6990165            <NA>
48  2021-11-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7481621                  7067100            <NA>
49  2021-12-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7527821                  7138275            <NA>
50  2021-12-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7575290                  7209137            <NA>
51  2021-12-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7618376                  7272440            <NA>
52  2021-12-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7635934                  7298643            <NA>
53  2022-01-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7647865                  7315934            <NA>
54  2022-01-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7663644                  7343045            <NA>
55  2022-01-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7689283                  7396733            <NA>
56  2022-01-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7712221                  7440722            <NA>
57  2022-01-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7727178                  7467530            <NA>
58  2022-02-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7737427                  7488672            <NA>
59  2022-02-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7745739                  7510002            <NA>
60  2022-02-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7751754                  7527206            <NA>
61  2022-02-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7756652                  7541261            <NA>
62  2022-03-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7760224                  7550484            <NA>
63  2022-03-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7763294                  7557824            <NA>
64  2022-03-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7767318                  7565207            <NA>
65  2022-03-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7770139                  7570543            <NA>
66  2022-04-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7772618                  7574808            <NA>
67  2022-04-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7774842                  7578286            <NA>
68  2022-04-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7776652                  7581086            <NA>
69  2022-04-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7778812                  7584266            <NA>
70  2022-05-01   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7781099                  7587569            <NA>
71  2022-05-08   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7783368                  7590490            <NA>
72  2022-05-15   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7785718                  7593510            <NA>
73  2022-05-22   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7787923                  7596641            <NA>
74  2022-05-29   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7789604                  7599524            <NA>
75  2022-06-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7791181                  7602506            <NA>
76  2022-06-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7792252                  7604892            <NA>
77  2022-06-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7793464                  7607409            <NA>
78  2022-06-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7794366                  7609221            <NA>
79  2022-07-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7795346                  7610930            <NA>
80  2022-07-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7796325                  7612308            <NA>
81  2022-07-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7797439                  7613615            <NA>
82  2022-07-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7798349                  7614651            <NA>
83  2022-07-31   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7799249                  7615536            <NA>
84  2022-08-07   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7800196                  7616417            <NA>
85  2022-08-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7801148                  7617435            <NA>
86  2022-08-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7802000                  7618460            <NA>
87  2022-08-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7802736                  7619252            <NA>
88  2022-09-04   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7803591                  7620225            <NA>
89  2022-09-11   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7804759                  7621308            <NA>
90  2022-09-18   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7805943                  7622495            <NA>
91  2022-09-25   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7807074                  7623644            <NA>
92  2022-10-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7808163                  7624819            <NA>
93  2022-10-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7809028                  7625864            <NA>
94  2022-10-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7809837                  7626821            <NA>
95  2022-10-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7810530                  7627737            <NA>
96  2022-10-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7811112                  7628588            <NA>

[51 rows x 8 columns]
","51 rows have been removed. That is more than maximum allowed (10) by make_monotonic() - check the data. Check 
          date location                                         source_url  ... people_vaccinated  people_fully_vaccinated  total_boosters
46  2021-11-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7392904                  6925338            <NA>
47  2021-11-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7436125                  6990165            <NA>
48  2021-11-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7481621                  7067100            <NA>
49  2021-12-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7527821                  7138275            <NA>
50  2021-12-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7575290                  7209137            <NA>
51  2021-12-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7618376                  7272440            <NA>
52  2021-12-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7635934                  7298643            <NA>
53  2022-01-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7647865                  7315934            <NA>
54  2022-01-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7663644                  7343045            <NA>
55  2022-01-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7689283                  7396733            <NA>
56  2022-01-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7712221                  7440722            <NA>
57  2022-01-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7727178                  7467530            <NA>
58  2022-02-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7737427                  7488672            <NA>
59  2022-02-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7745739                  7510002            <NA>
60  2022-02-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7751754                  7527206            <NA>
61  2022-02-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7756652                  7541261            <NA>
62  2022-03-06   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7760224                  7550484            <NA>
63  2022-03-13   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7763294                  7557824            <NA>
64  2022-03-20   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7767318                  7565207            <NA>
65  2022-03-27   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7770139                  7570543            <NA>
66  2022-04-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7772618                  7574808            <NA>
67  2022-04-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7774842                  7578286            <NA>
68  2022-04-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7776652                  7581086            <NA>
69  2022-04-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7778812                  7584266            <NA>
70  2022-05-01   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7781099                  7587569            <NA>
71  2022-05-08   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7783368                  7590490            <NA>
72  2022-05-15   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7785718                  7593510            <NA>
73  2022-05-22   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7787923                  7596641            <NA>
74  2022-05-29   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7789604                  7599524            <NA>
75  2022-06-05   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7791181                  7602506            <NA>
76  2022-06-12   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7792252                  7604892            <NA>
77  2022-06-19   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7793464                  7607409            <NA>
78  2022-06-26   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7794366                  7609221            <NA>
79  2022-07-03   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7795346                  7610930            <NA>
80  2022-07-10   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7796325                  7612308            <NA>
81  2022-07-17   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7797439                  7613615            <NA>
82  2022-07-24   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7798349                  7614651            <NA>
83  2022-07-31   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7799249                  7615536            <NA>
84  2022-08-07   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7800196                  7616417            <NA>
85  2022-08-14   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7801148                  7617435            <NA>
86  2022-08-21   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7802000                  7618460            <NA>
87  2022-08-28   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7802736                  7619252            <NA>
88  2022-09-04   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7803591                  7620225            <NA>
89  2022-09-11   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7804759                  7621308            <NA>
90  2022-09-18   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7805943                  7622495            <NA>
91  2022-09-25   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7807074                  7623644            <NA>
92  2022-10-02   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7808163                  7624819            <NA>
93  2022-10-09   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7809028                  7625864            <NA>
94  2022-10-16   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7809837                  7626821            <NA>
95  2022-10-23   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7810530                  7627737            <NA>
96  2022-10-30   Sweden  https://fohm.se/smittskydd-beredskap/utbrott/a...  ...           7811112                  7628588            <NA>

[51 rows x 8 columns]"
cowidev.vax.batch.switzerland,157.66,True,2022-11-10T07:03:41,,
cowidev.vax.batch.trinidad_and_tobago,1.63,True,2022-11-10T07:01:15,,
cowidev.vax.batch.ukraine,,,2022-11-10T07:01:14,,
cowidev.vax.batch.united_kingdom,9.81,True,2022-11-10T07:01:24,,
cowidev.vax.batch.united_states,16.56,True,2022-11-10T07:01:32,,
cowidev.vax.batch.uruguay,1.08,True,2022-11-10T07:01:25,,
cowidev.vax.batch.zimbabwe,1.12,True,2022-11-10T07:01:25,,
cowidev.vax.incremental.africacdc,,,2022-11-10T07:01:25,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-10T07:01:25,,
cowidev.vax.incremental.aruba,1.25,True,2022-11-10T07:01:26,,
cowidev.vax.incremental.azerbaijan,,,2022-11-10T07:01:25,,
cowidev.vax.incremental.bahrain,1.29,True,2022-11-10T07:01:27,,
cowidev.vax.incremental.bangladesh,20.48,True,2022-11-10T07:01:46,,
cowidev.vax.incremental.barbados,,,2022-11-10T07:01:26,,
cowidev.vax.incremental.brazil,0.05,True,2022-11-10T07:01:26,,
cowidev.vax.incremental.bulgaria,1.13,True,2022-11-10T07:01:27,,
cowidev.vax.incremental.china,34.39,True,2022-11-10T07:02:01,,
cowidev.vax.incremental.costa_rica,,,2022-11-10T07:01:27,,
cowidev.vax.incremental.croatia,0.18,True,2022-11-10T07:01:27,,
cowidev.vax.incremental.cuba,2.12,True,2022-11-10T07:01:29,,
cowidev.vax.incremental.curacao,0.37,True,2022-11-10T07:01:30,,
cowidev.vax.incremental.cyprus,0.97,True,2022-11-10T07:01:31,,
cowidev.vax.incremental.dominican_republic,7.82,True,2022-11-10T07:01:39,,
cowidev.vax.incremental.el_salvador,0.59,True,2022-11-10T07:01:33,,
cowidev.vax.incremental.faeroe_islands,0.39,True,2022-11-10T07:01:33,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-10T07:01:33,,
cowidev.vax.incremental.finland,0.25,True,2022-11-10T07:01:33,,
cowidev.vax.incremental.gabon,,,2022-11-10T07:01:33,,
cowidev.vax.incremental.georgia,0.5,True,2022-11-10T07:01:34,,
cowidev.vax.incremental.greenland,0.58,False,2022-11-10T08:10:10,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 74, in main
    Greenland().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 61, in export
    data = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 18, in read
    data = self._parse_data(soup)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 22, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 26, in _parse_data_metrics
    dose_1 = clean_count(re.search(r""Innuttaasut ([\d\.]+)"", counters[1].parent.find_all(""dd"")[-1].text).group(1))
IndexError: list index out of range
",list index out of range
cowidev.vax.incremental.guatemala,,,2022-11-10T07:01:34,,
cowidev.vax.incremental.guernsey,0.27,False,2022-11-10T08:10:10,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 61, in main
    Guernsey().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 50, in export
    data = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 15, in read
    df = self.parse_data(soup)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 31, in parse_data
    ds.loc[ds[0] == ""Total doses"", 1].values[0].replace(""*"", """"),
IndexError: index 0 is out of bounds for axis 0 with size 0
",index 0 is out of bounds for axis 0 with size 0
cowidev.vax.incremental.hungary,1.34,True,2022-11-10T07:01:36,,
cowidev.vax.incremental.iceland,0.74,True,2022-11-10T07:01:37,,
cowidev.vax.incremental.india,0.86,True,2022-11-10T07:01:38,,
cowidev.vax.incremental.iran,,,2022-11-10T07:01:38,,
cowidev.vax.incremental.isle_of_man,0.81,True,2022-11-10T07:01:38,,
cowidev.vax.incremental.jamaica,1.95,True,2022-11-10T07:01:40,,
cowidev.vax.incremental.kazakhstan,9.6,True,2022-11-10T07:01:48,,
cowidev.vax.incremental.kosovo,1.85,True,2022-11-10T07:01:42,,
cowidev.vax.incremental.kyrgyzstan,6.15,True,2022-11-10T07:01:48,,
cowidev.vax.incremental.laos,2.11,True,2022-11-10T07:01:48,,
cowidev.vax.incremental.macao,43.75,False,2022-11-10T08:10:54,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 22, in read
    data = self._parse_data(elem)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 50, in _parse_data
    df = self._parse_pdf_table(url)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 33, in _parse_pdf_table
    raise ValueError(""New columns added!"")
ValueError: New columns added!
",New columns added!
cowidev.vax.incremental.moldova,,,2022-11-10T07:01:48,,
cowidev.vax.incremental.monaco,29.3,True,2022-11-10T07:02:17,,
cowidev.vax.incremental.mongolia,0.83,True,2022-11-10T07:01:49,,
cowidev.vax.incremental.montenegro,0.1,True,2022-11-10T07:01:49,,
cowidev.vax.incremental.morocco,,,2022-11-10T07:01:49,,
cowidev.vax.incremental.myanmar,,,2022-11-10T07:01:49,,
cowidev.vax.incremental.nepal,,,2022-11-10T07:01:49,,
cowidev.vax.incremental.north_macedonia,,,2022-11-10T07:01:49,,
cowidev.vax.incremental.northern_cyprus,0.72,True,2022-11-10T07:01:50,,
cowidev.vax.incremental.paho,44.37,False,2022-11-10T08:11:39,"Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 191, in main
    PAHO().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 186, in export
    df = self.read().pipe(self.pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 51, in _parse_data
    driver.find_element_by_id(""tableauTabbedNavigation_tab_2"").click()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""tableauTabbedNavigation_tab_2""]""}
  (Session info: headless chrome=107.0.5304.87)

","Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""tableauTabbedNavigation_tab_2""]""}
  (Session info: headless chrome=107.0.5304.87)
"
cowidev.vax.incremental.pakistan,1.35,True,2022-11-10T07:02:02,,
cowidev.vax.incremental.philippines,,,2022-11-10T07:02:02,,
cowidev.vax.incremental.playground_mojmir,4.76,True,2022-11-10T07:02:07,,
cowidev.vax.incremental.poland,0.47,True,2022-11-10T07:02:08,,
cowidev.vax.incremental.qatar,,,2022-11-10T07:02:08,,
cowidev.vax.incremental.russia,40.02,False,2022-11-10T08:12:19,"Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x12d5c1d20>, 'Connection to gogov.ru timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gogov.ru', port=443): Max retries exceeded with url: /articles/covid-v-stats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x12d5c1d20>, 'Connection to gogov.ru timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='gogov.ru', port=443): Max retries exceeded with url: /articles/covid-v-stats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x12d5c1d20>, 'Connection to gogov.ru timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='gogov.ru', port=443): Max retries exceeded with url: /articles/covid-v-stats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x12d5c1d20>, 'Connection to gogov.ru timed out. (connect timeout=20)'))"
cowidev.vax.incremental.saint_lucia,,,2022-11-10T07:02:08,,
cowidev.vax.incremental.serbia,6.51,True,2022-11-10T07:02:15,,
cowidev.vax.incremental.south_africa,8.51,True,2022-11-10T07:02:23,,
cowidev.vax.incremental.spain,11.32,True,2022-11-10T07:02:29,,
cowidev.vax.incremental.sri_lanka,,,2022-11-10T07:02:21,,
cowidev.vax.incremental.suriname,14.3,True,2022-11-10T07:02:36,,
cowidev.vax.incremental.taiwan,5.83,True,2022-11-10T07:02:29,,
cowidev.vax.incremental.thailand,3.71,True,2022-11-10T07:02:33,,
cowidev.vax.incremental.turkey,40.02,False,2022-11-10T08:16:59,"Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x11e515870>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11e515870>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/Users/edouard/git/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/Users/edouard/.pyenv/versions/3.10.0/envs/covid/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11e515870>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11e515870>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-10T07:02:33,,
cowidev.vax.incremental.vietnam,,,2022-11-10T07:02:33,,
cowidev.vax.incremental.who,3.75,True,2022-11-10T07:02:36,,
cowidev.vax.incremental.zambia,0.84,True,2022-11-10T07:02:37,,
